# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 412265f997bf78e55d6a3b148ac4b698698315ef18b60d9ce613a0fb93ff99f6bec2409427225c88963926bd1992957ecd13c1f022537d815dbbeb3fc1345e58

test:
  secret_key_base: d92337b6db72112f5daf8cbc22247455b0ae38d667629ec15e9942ebbe4ce025b51e7d7f07cf815cfb191b072e4abecdb1f840ec3a1944b6f46b9968eabaab3a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
